### ISSUE TITLE
TMC2209 driver spec

### ISSUE THREAD

**Issue by samuk** [idea7-cc/TEC-Bots#2]
Would you anticipate any issues with using a TMC2209 driver in place of the DRV8825? It should be quieter? https://3dwork.io/en/tmc-drivers/

**Comment by chrishthompson** [comment]
Hey samuk!  I don't remember if I tried a TMC2209 driver but I probably did.  It should work.  One thing I'd consider is that quieter micro stepping modes can come with a loss of torque.

I haven't thought about this for a while, but a few things I'd recommend you consider:
- When I used an Arduino Nano clone to run GRBL, it was a workaround...it worked fine, but now that GRBL is ported to ESP-32 thanks to this project: https://github.com/bdring/Grbl_Esp32 and now this project: https://github.com/bdring/FluidNC, I think it's much better to run it directly from the M5 stack or other esp-32 board.
- I won't be much help because I'm too wrapped up in client projects these days...you might be better off with a project that has more of an active community.
- If you want to build it anyway, be ready for some of your own troubleshooting and development.
- If you do decide to build it, and you can't find a part you need, let me know.  I might have a spare.

**Comment by samuk** [comment]
Thanks for the info. I did wonder about using ESP32 directly as per: https://www.tindie.com/products/33366583/tmc2209-penlaser-controller/ 

I'm looking to do a 100% open hardware ESP32 bot (for uROS) & I'd like to have compatibility with M5 core, so I only know of your project and https://github.com/meganetaaan/M5Mouse. 

M5Mouse has a nice motor shield that fits in M5Stack, but they are using DC motors, which are hard to waterproof. My mental roadmap includes an outdoor robot and IP65 steppers are fairly available.

Some rough ideas for my project are here if you're interested: https://cloud.transition-space.org/apps/onlyoffice/s/KyTnsYjs4GRkXjZ

I'm leaning towards designing (with others) my own M5 stack 'Open Core' and 'Open Stepper driver' at the moment. But I've never designed a PCB, so expect a steep learning curve!

The nice thing about M5 is you could plug in the Odrive shield, or Canbus and start building more precise and powerful robots from the same core.
